---

- name: apt | cache | update
  apt: update_cache=yes
  when: do_install|bool

- name: romanesco | deps | install
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-dev
    - python-pip
    - python-virtualenv
    - libjpeg-dev
    - zlib1g-dev
  when: do_install|bool

- name: romanesco | service | stop
  service:
    name: romanesco
    state: stopped
  ignore_errors: true
  when: stop_services|bool

- name: romanesco | install root | delete
  file:
    path: "{{ romanesco_install_root }}"
    state: absent
  when: remove_install_root|bool

- name: romanesco | data root | delete
  file:
    path: "{{ romanesco_data_root }}"
    state: absent
  when: remove_data_root|bool

- name: romanesco | install parent | create
  file:
    path: "{{ romanesco_install_root }}"
    state: directory
  when: do_install|bool

- name: romanesco | data root | create
  file:
    path: "{{ romanesco_data_root }}"
    state: directory
    mode: 0755
    owner: "{{ romanesco_user }}"
    group: "{{ romanesco_group }}"
  when: do_install|bool

- name: romanesco | repo | sync
  command: >
    rsync -avz --exclude=.git
    "{{ romanesco_git_work_dir }}/"
    "{{ romanesco_install_root }}"
  when: do_install|bool

- name: pip
  pip:
    requirements: "{{ romanesco_install_root }}/{{ item }}"
    virtualenv: "{{venv_root}}"
  with_items:
    - requirements.txt
    - romanesco/plugins/r/requirements.txt
  when: do_install|bool

- name: romanesco | script | service | generate
  template:
    src: run-service.j2
    dest: "{{ romanesco_install_root }}/run-service"
    mode: 0755
  when: do_install|bool

- name: romanesco | conf | set
  template:
    src: worker.local.cfg.j2
    dest: "{{ romanesco_install_root }}/romanesco/worker.local.cfg"
    mode: 0644
  when: do_install|bool


- name: romanesco | conf | owner | set
  file:
    recurse: yes
    path: "{{ romanesco_install_root }}"
    group: "{{ romanesco_group }}"
    mode: 0755
    owner: "{{ romanesco_user }}"
  when: do_install|bool
