---
  - name: Add MongoDB repo key
    command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
    sudo: yes
    tags: girder

  - name: Add MongoDB repo
    apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' update_cache=yes
    sudo: yes
    tags: girder


  - name: Install MongoDb
    apt: name={{ item }} state=present
    sudo: yes
    with_items:
      - mongodb-org-server
      - mongodb-org-shell

  - name: service | stop
    service:
        name: mongod
        state: stopped
    when: do_install|bool

  - name: configure | log file | owner | set
    file:
        path: /var/log/mongodb.log
        state: touch
        owner: mongodb
    when: do_install|bool

  - name: configure | old log dir | remove
    file:
        path: /var/log/mongodb
        state: absent
    when: do_install|bool

  - name: configure
    template:
        src: mongodb.conf.j2
        dest: /etc/mongod.conf
    when: do_install|bool
