---
- name: Install flow system dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-dev
    - python-pip
    - python-numpy
  become: yes

- name: Ensure flow directory exists
  file:
    path: "{{ flow_path }}"
    state: directory
    group: "{{ ansible_user_id }}"
    owner: "{{ ansible_user_id }}"
    mode: 0755
  become: yes

- name: Get flow from github
  git:
    repo: https://github.com/Kitware/flow.git
    version: "{{ flow_version }}"
    dest: "{{ flow_path }}"
    update: no
    force: no
    accept_hostkey: yes
