---

# Setup systemd service
- block:
    - name: Install service
      template:
        src: "daemon/girder.service.j2"
        dest: "/etc/systemd/system/girder.service"

    - name: (Re)start service
      systemd:
        name: girder
        daemon_reload: yes
        state: restarted
      when: girder_start

    - name: Enable/Disable Girder service on boot
      systemd:
        name: girder
        daemon_reload: yes
        enabled: "{{ girder_enabled }}"
  become: yes
  become_user: root
