# Configure plugins and girder
- hosts: girder
  sudo: yes
  tasks:
    - name: Create an 'Girder' user
      girder:
        port: 8080
        user:
          firstName: "Girder"
          lastName: "Girder"
          login: "girder"
          password: "girder"
          email: "girder@example.com"
          admin: yes
        state: present

    - name: Activate Plugins
      girder:
        port: 8080
        username: "girder"
        password: "girder"
        plugins:
          - girder_worker
          - flow
        state: present

    - name: Create assetstore directory
      file:
        path: "/opt/data"
        owner: "girder"
        group: "girder"
        state: directory

    - name: Create filesystem assetstore
      girder:
        port: 8080
        username: "girder"
        password: "girder"
        assetstore:
          name: "Filesystem Assetstore"
          type: "filesystem"
          root: "/opt/data"
          current: true
        state: present


    - name: Restart Flow
      girder:
        port: 8080
        username: "girder"
        password: "girder"
        put:
          path: "system/restart"
