---

- name: apt | cache | update
  apt: update_cache=yes
  when: do_install|bool

- name: girder_worker | deps | install
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-dev
    - python-pip
    - python-virtualenv
    - libjpeg-dev
    - zlib1g-dev
  when: do_install|bool

- name: girder_worker | service | stop
  service:
    name: girder_worker
    state: stopped
  ignore_errors: true
  when: stop_services|bool

- name: girder_worker | install root | delete
  file:
    path: "{{ girder_worker_install_root }}"
    state: absent
  when: remove_install_root|bool

- name: girder_worker | data root | delete
  file:
    path: "{{ girder_worker_data_root }}"
    state: absent
  when: remove_data_root|bool

- name: girder_worker | install parent | create
  file:
    path: "{{ girder_worker_install_root }}"
    state: directory
  when: do_install|bool

- name: girder_worker | data root | create
  file:
    path: "{{ girder_worker_data_root }}"
    state: directory
    mode: 0755
    owner: "{{ girder_worker_user }}"
    group: "{{ girder_worker_group }}"
  when: do_install|bool

- name: girder_worker | repo | sync
  command: >
    rsync -avz --exclude=.git
    "{{ girder_worker_git_work_dir }}/"
    "{{ girder_worker_install_root }}"
  when: do_install|bool

- name: pip
  pip:
    requirements: "{{ girder_worker_install_root }}/{{ item }}"
    virtualenv: "{{venv_root}}"
  with_items:
    - requirements.txt
    - girder_worker/plugins/r/requirements.txt
  when: do_install|bool

- name: girder_worker | script | service | generate
  template:
    src: run-service.j2
    dest: "{{ girder_worker_install_root }}/run-service"
    mode: 0755
  when: do_install|bool

- name: girder_worker | conf | set
  template:
    src: worker.local.cfg.j2
    dest: "{{ girder_worker_install_root }}/girder_worker/worker.local.cfg"
    mode: 0644
  when: do_install|bool


- name: girder_worker | conf | owner | set
  file:
    recurse: yes
    path: "{{ girder_worker_install_root }}"
    group: "{{ girder_worker_group }}"
    mode: 0755
    owner: "{{ girder_worker_user }}"
  when: do_install|bool
