---
- name: Ensure girder_worker directory exists
  file:
    path: "{{ girder_worker_path }}"
    state: directory
    group: "{{ ansible_user_id }}"
    owner: "{{ ansible_user_id }}"
    mode: 0755
  become: yes

- name: Get girder_worker from github
  git:
    repo: https://github.com/girder/girder_worker.git
    version: "{{ girder_worker_version }}"
    dest: "{{ girder_worker_path }}"
    update: no
    force: no
    accept_hostkey: yes

- include: pip.yml
  become: yes
  when: girder_worker_virtualenv is not defined

- include: pip.yml
  when: girder_worker_virtualenv is defined

- name: Install girder_worker service
  template:
    src: "upstart.girder_worker.conf.j2"
    dest: "/etc/init/girder_worker.conf"
  become: yes
