- name: Update Pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ girder_worker_virtualenv | default(omit) }}"

- name: Install Girder Python requirements
  pip:
    requirements: "{{ girder_worker_path }}/requirements.txt"
    virtualenv: "{{ girder_worker_virtualenv | default(omit) }}"

- name: Install Girder and plugin requirements
  pip:
    name: "."
    extra_args: "-e"
    chdir: "{{ girder_worker_path }}"
    virtualenv: "{{ girder_worker_virtualenv | default(omit) }}"

- name: Check if requirements.txt for each plugin exists
  stat:
    path: "{{ girder_worker_path }}/girder_worker/plugins/{{ item }}/requirements.txt"
  with_items: "{{ girder_worker_plugins }}"
  register: requirements_files

- name: Install Girder Worker plugin requirements
  pip:
    requirements: "{{ item.stat.path }}"
    virtualenv: "{{ girder_worker_virtualenv | default(omit) }}"
  with_items: "{{ requirements_files.results }}"
  when: item.stat.exists
