---

dependencies:
  - role: romanesco-variables
  - role: upstart
    name: romanesco
    user: "{{ romanesco_user }}"
    group: "{{ romanesco_group }}"
    description: Romanesco Execution Engine Service
    command: "{{ romanesco_install_root }}/run-service"
    when: do_install|bool

